name: Todo App CI

on:
  push:
    paths:
      - 'todoProject/**'
  pull_request:
    paths:
      - 'todoProject/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          cd todoProject
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          cd todoProject
          python manage.py test
